import pImg1 from "../../../../assets/propery_list/1.png"
import pImg2 from "../../../../assets/propery_list/2.png"
import pImg3 from "../../../../assets/propery_list/3.png"
import pImg4 from "../../../../assets/propery_list/4.png"
import pImg5 from "../../../../assets/propery_list/5.png"
import pImg6 from "../../../../assets/propery_list/6.png"

export const propertiesData = [
  {
    property_id: "P001",
    image_url: pImg1,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Residential"
  },
  {
    property_id: "P002",
    image_url: pImg2,
    price: "$200,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Residential"
  },
  {
    property_id: "P003",
    image_url: pImg3,
    price: "$30,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Residential"
  },
  {
    property_id: "P004",
    image_url: pImg4,
    price: "$100,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Residential"
  },
  {
    property_id: "P005",
    image_url: pImg5,
    price: "$39,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Residential"
  },
  {
    property_id: "P006",
    image_url: pImg6,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Residential"
  },
  {
    property_id: "P008",
    image_url: pImg5,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Commercial"
  },
  {
    property_id: "P009",
    image_url: pImg4,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Commercial"
  },
  {
    property_id: "P010",
    image_url: pImg3,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Commercial"
  },
  {
    property_id: "P011",
    image_url: pImg2,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Commercial"
  },
  {
    property_id: "P012",
    image_url: pImg1,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Commercial"
  },
  {
    property_id: "P013",
    image_url: pImg1,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Apartment"
  },
  {
    property_id: "P014",
    image_url: pImg2,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Apartment"
  },
  {
    property_id: "P015",
    image_url: pImg3 ,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Apartment"
  },
  {
    property_id: "P016",
    image_url: pImg4,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Apartment"
  },
  {
    property_id: "P017",
    image_url: pImg5,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: false,
    category: "Apartment"
  },
  {
    property_id: "P018",
    image_url: pImg6,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Apartment"
  },
  {
    property_id: "P019",
    image_url: pImg6,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Office space"
  },
  {
    property_id: "P020",
    image_url: pImg5,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Office space"
  },
  {
    property_id: "P021",
    image_url: pImg4,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Office space"
  },
  {
    property_id: "P022",
    image_url: pImg3,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Office space"
  },
  {
    property_id: "P023",
    image_url: pImg2,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Office space"
  },
  {
    property_id: "P024",
    image_url: pImg1,
    price: "$300,000 USD",
    text1: "Classic charm",
    text2: "Georgian town houses in the heart of the city",
    bed: "2 bed",
    bathroom: "1 bathroom",
    distance: "70 m2",
    forSale: true,
    category: "Office space"
  },
];
